server:
  port: 8080
  servlet:
    context-path: /api/admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/chain?characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


