server:
  port: 8080
  servlet:
    context-path: /monitor/admin

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monitor?characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#

